- Python/setup.py
> Use latest v2 request

- Python/dawgie/context.py
- Python/dawgie/pl/logger/__init__.py
> issue 8: log backup count

- Python/dawgie/tools/submit.py
> issue 11: no email

- Python/dawgie/db/shelf.py
- Test/test_07.py
> Issue 16: add new targets when detected

- Python/dawgie/security.py
> issue 13: adapt to gnupg version

- .ci/deploy_01.sh
- Python/dawgie/__init__.py
- Python/dawgie/pl/dag.py
- Python/dawgie/tools/compliant.py
- Python/dawgie/util.py
- Test/ae/feedback/bot.py
- Test/test_08.py
> Issue 18: ref verification

- .ci/pypi.sh
> issue 25: PyPI script

- Python/dawgie/tools/compliant.py
- Python/dawgie/tools/dag.py
- Test/bae/__init__.py
- Test/bae/network/__init__.py
- Test/bae/network/bot.py
> Issue 27: expand compliant checks

- .ci/deploy_05.sh
- .ci/exercise_01.sh
> Issue 20: correct substring

- Python/dawgie/db/shelf.py
- Python/dawgie/fe/app.py
- Python/dawgie/pl/resources.py
> Issue 29: filter defaults

- Python/dawgie/fe/app.py
- Python/dawgie/pl/logger/fe.py
> issue 31: missing log page

- Python/dawgie/context.py
> issue 42: quick fix

- Python/dawgie/context.py
- Python/dawgie/db/shelf.py
- Python/dawgie/pl/aws.py
- Python/dawgie/pl/farm.py
- Python/dawgie/pl/logger/__init__.py
> Issue 47: backlog

- Python/dawgie/__init__.py
- Python/dawgie/pl/schedule.py
- Python/dawgie/tools/compliant.py
- Test/ae/network/__init__.py
- Test/bae/network/__init__.py
- Test/test_04.py
- Test/test_06.py
- Test/test_09.py
> Issue 44: fixing up scheduler

- Python/dawgie/db/tools/post2shelve.py
> issue 51: patch post2shelve

- Python/dawgie/de/html.py
> issue 53: update bokeh

- Python/dawgie/pl/farm.py
- Python/dawgie/pl/schedule.py
- Test/test_06.py
- Test/test_10.py
> issue 55: test and 

- Python/dawgie/de/__init__.py
- Python/dawgie/fe/__init__.py
> adjust factories

- Python/dawgie/db/post.py
> issue 66: post updates

- Python/dawgie/db/post.py
> pass current environment

- Python/dawgie/de/__init__.py
> issue 77: emergency fix

- .ci/pylint.rc
- Python/dawgie/db/__init__.py
- Python/dawgie/fe/__init__.py
- Python/dawgie/fe/app.py
- Python/dawgie/fe/submit.py
- Python/dawgie/fe/svrender.py
- Python/dawgie/pl/start.py
- Python/dawgie/pl/util.py
- Python/dawgie/tools/compliant.py
- Python/dawgie/tools/submit.py
- Test/ae/disk/__init__.py
- Test/ae/noio/__init__.py
> issue 80: fix auto merge

- Python/dawgie/fe/app.py
> issue 85: broken view

- Python/dawgie/fe/__init__.py
- Python/dawgie/fe/app.py
- Python/dawgie/fe/submit.py
- Python/dawgie/fe/svrender.py
> Issue 87: clean up front-end

- .ci/Dockerfile.py
- .ci/pylint.rc
- Python/dawgie/context.py
- Python/dawgie/fe/__init__.py
- Python/dawgie/fe/__main__.py
- Python/dawgie/pl/state.py
- Python/requirements.txt
> Issue 76: support https

- Python/dawgie/context.py
- Python/dawgie/fe/submit.py
- Python/dawgie/tools/submit.py
> Issue 84: remove hardcoded email alerts

- .ci/pylint.rc
- Python/dawgie/db/post.py
- Python/dawgie/db/shelf.py
- Python/dawgie/db/util.py
- Python/dawgie/fe/__init__.py
- Python/dawgie/fe/__main__.py
- Python/dawgie/fe/app.py
- Python/dawgie/fe/submit.py
- Python/dawgie/pl/farm.py
- Python/dawgie/pl/start.py
- Python/dawgie/pl/state.py
- Python/dawgie/tools/trace.py
- Test/test_10.py
> Issue 90: excise SDP

- Python/dawgie/de/html.py
Merge from issue_75-1.2.x to Release-1.2.x. Only a single file was changed: Python/dawgie/de/html.py. Only changes to the single file were cherry-picked over. Note that issue_75-1.2.x was cut from Release-1.2.x tonight.
> Issue 75 1.2.x (issue_75-1.2.x to Release-1.2.x)

- Python/dawgie/de/html.py
* issue_75: Changes, including fix for bug with duplicate tags, spacing reformat, fix for lists not using 'li', fix to allow 'void' tags proper formatting, addition of capacity to add raw css and stylesheets, addition of pre tag, modify add_primitive to display inline with add_declaration, addition of class and id attributes, spacing tweaks per PEP8, regroup writing of configuration (head) versus presentation (body) tags, disable writing of primitives after declarations since they are now written inline. ...
* issue_75: Changed approach to keep copy of old methods guaranteeing strict backwards compatibility. Also, new method will use inherited __content value to append, then guaranteeing exact ordering with all other subclasses. Touchpoint. ... TO-DO: Modify div for ease-of-use to …
> Issue 75 1.2.x (issue_75-1.2.x to Release-1.2.x) (#93)

- Python/dawgie/db/shelf.py
> use a generator

- Python/dawgie/__init__.py
- Python/dawgie/tools/compliant.py
- Test/ae/disk/__init__.py
- Test/ae/feedback/__init__.py
- Test/ae/network/__init__.py
- Test/ae/noio/__init__.py
- Test/ae/review/__init__.py
- Test/bae/network/__init__.py
> Issue 100: enhance rule 01

- Python/dawgie/pl/__init__.py
- Python/dawgie/pl/aws.py
- Python/dawgie/pl/farm.py
- Python/dawgie/pl/schedule.py
- Python/dawgie/pl/start.py
- Python/dawgie/pl/state.py
> issue 108: improve logging

- Python/dawgie/pl/state.py
- Test/test_02.py
> Issue 101: thread state changes

- Python/dawgie/fe/app.py
- Python/setup.py
> issue 114: improve version information

- Python/dawgie/db/util.py
> 106: rotate error

- Python/dawgie/pl/__init__.py
- Python/dawgie/pl/__main__.py
- Python/dawgie/pl/farm.py
- Python/dawgie/pl/schedule.py
- Python/dawgie/pl/state.py
- Python/dawgie/pl/worker/aws.py
- Test/test_02.py
> Issue 111: redo LogDeferredException

- Python/dawgie/db/shelf.py
Closes #32
Made shelf echo post.
> issue 32: aspects implemented similarly

- Python/dawgie/pl/farm.py
- Test/test_10.py
> add version information

- Python/dawgie/fe/app.py
- Python/dawgie/pl/schedule.py
- Test/test_06.py
> Issue 129: implement externalization of events

- Test/test_06.py
> Issue 128: check on events

- Python/dawgie/pl/farm.py
- Python/dawgie/pl/jobinfo.py
- Python/dawgie/pl/schedule.py
- Python/dawgie/pl/worker/aws.py
- Python/dawgie/pl/worker/cluster.py
- Test/test_06.py
- Test/test_10.py
> Issue 60: leaving state vector empty

- Python/dawgie/__init__.py
- Python/dawgie/db/post.py
- Python/dawgie/db/shelf.py
- Python/dawgie/pl/schedule.py
- Test/test_06.py
> update new values

- Python/dawgie/pl/auto.py
- Python/dawgie/pl/promotion.py
- Python/dawgie/pl/schedule.py
- Test/test_12.py
Closes #136 
The changes keep current behavior but concentrate where behavioral changes in the future for promotion has to take place.
> Issue 136: add promotion hooks

- Python/dawgie/fe/__init__.py
> issue_146: fix security problem

- Python/dawgie/tools/compliant.py
- Test/ae/disk/__init__.py
- Test/ae/feedback/__init__.py
- Test/ae/network/__init__.py
- Test/ae/noio/__init__.py
- Test/ae/review/__init__.py
> issue #151 - fix first param

- .ci/util.sh
- Python/dawgie/db/tools/inter.py
> Issue #153 : scripts to help inter data

- Python/dawgie/db/post.py
> issue 164: simple fix

- Python/dawgie/pl/__main__.py
> issue 162: make them match at warning

- Python/dawgie/db/post.py
> issue 170: postgres processing error

- Python/dawgie/db/tools/post2shelve.py
> issue 172: performance of post2shelve

- Python/dawgie/tools/trace.py
> issue 174: archive hangs

- Python/dawgie/db/post.py
> issue 181: post.trace() invalid version determination

- Python/dawgie/__init__.py
- Python/dawgie/db/__init__.py
- Python/dawgie/db/post.py
- Python/dawgie/db/shelf.py
- Python/dawgie/db/test.py
- Test/Integration/ae/prime/bot.py
- Test/Integration/check_06.sh
- Test/test_13.py
> Issue 183: extend interface

- Python/dawgie/db/util/aspect.py
- Test/test_13.py
> Issue 185: infinite recursion

- Python/dawgie/db/post.py
> issue_186: maybe fix timelines

- Python/dawgie/db/post.py
> issue 198: add more context to the error message

- Python/dawgie/context.py
> issue 195: stronger check for true

- Python/dawgie/context.py
> issue 196: add default value to help

- Python/dawgie/db/shelve/comms.py
- Python/dawgie/pl/promotion.py
- Python/dawgie/pl/schedule.py
- Python/requirements.txt
- Test/mock.py
- Test/test_05.py
- Test/test_06.py
- Test/test_10.py
- Test/test_12.py
- Test/test_13.py
- Test/test_15.py
> Issue 194: updates to scheduler and testing of it

- Python/dawgie/db/tools/post2shelve.py
> issue 210: fixes for it to work

- Python/dawgie/db/shelve/__init__.py
- Python/dawgie/pl/scan.py
- Test/test_13.py
First clean up and show shelve works in general in real life.
> issue 199: verify promotion and shelve work in real life

- Python/dawgie/db/shelve/comms.py
- Python/dawgie/db/shelve/model.py
- Python/dawgie/db/shelve/util.py
- Python/dawgie/security.py
- Test/test_07.py
> 214: problem with shelve comm link

- Python/dawgie/db/__init__.py
- Python/dawgie/db/shelve/__init__.py
- Python/dawgie/db/shelve/util.py
- Test/test_13.py
> Issue 213: make db.reset() explicit

- Python/dawgie/__init__.py
- Python/dawgie/de/html.py
> 232: sytle can be blank

- Python/dawgie/util/args.py
- Test/test_03.py
> 236:  fix logging problem

- Python/dawgie/__init__.py
- Python/dawgie/db/__init__.py
- Python/dawgie/db/post.py
- Python/dawgie/db/shelve/__init__.py
- Python/dawgie/db/shelve/model.py
- Python/dawgie/util/metrics.py
> 235: add wall time

- .ci/Dockerfile.py
- Python/dawgie/db/tools/inter.py
- Python/requirements.txt
> 241: inter improvements

- .ci/exercise_01.sh
- Python/dawgie/pl/state.dot
- Python/dawgie/security.py
> Issue 248: complete exercise

- Python/dawgie/db/__init__.py
- Python/dawgie/fe/svrender.py
> 250: connect caller ID to view

- Python/dawgie/fe/__init__.py
- Python/dawgie/fe/app.py
> Issue 245: add a reset

- Python/dawgie/fe/app.py
> Issue 253: improve reset

- Python/dawgie/tools/submit.py
Closes #266 
extension of work in #267
> 266: use rebase instead

- Python/dawgie/fe/app.py
- Python/dawgie/pl/state.dot
> 277: archive is an array of strings

- .github/workflows/bandit_baseline.json
- .github/workflows/run.sh
- .github/workflows/static_analysis.yaml
- Python/dawgie/db/post.py
- Python/dawgie/fe/app.py
> 279: update postgresql interface

- Python/dawgie/tools/compliant.py
> 289: new rule for checking references
